### ISSUE TITLE
Crash when trying to show how install the extruder

### ISSUE THREAD

**Issue by Xyphenore** [oierbravo/create-mechanical-extruder#36]
### Describe the Bug

When trying to show how install the extruder, with the 'Z' key, like other block/machine of Create.
The game freezes and crash.

### Reproduction Steps

1. Install the mod.
2. Run the game with the output console.
3. Create or load a save
4. Try to maintain 'Z' on extruder block in the inventory.
5. The game freezes and crash.

### Expected Result

No crash.

### Operating System

Windows 10 22H2

### Mod Version

1.5.4d-9

### Minecraft Version

1.20.1

### Forge Version

47.1.47

### Other Mods

- Create: 0.5.1d

### Traceback

```
Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.tags.TagKey.f_203868_()" because "this.tag" is null
	at TRANSFORMER/create_mechanical_extruder@1.20.1-1.5.4.d-9/com.oierbravo.createmechanicalextruder.components.extruder.BiomeCondition$BiomeTagCondition.toStringInternal(BiomeCondition.java:194)
	at TRANSFORMER/create_mechanical_extruder@1.20.1-1.5.4.d-9/com.oierbravo.createmechanicalextruder.components.extruder.BiomeCondition.toString(BiomeCondition.java:146)
	at TRANSFORMER/create_mechanical_extruder@1.20.1-1.5.4.d-9/com.oierbravo.createmechanicalextruder.components.extruder.ExtrudingBehaviour.write(ExtrudingBehaviour.java:60)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.blockEntity.SmartBlockEntity.lambda$write$1(SmartBlockEntity.java:92)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.blockEntity.SmartBlockEntity.forEachBehaviour(SmartBlockEntity.java:179)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.blockEntity.SmartBlockEntity.write(SmartBlockEntity.java:92)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.content.kinetics.base.KineticBlockEntity.write(KineticBlockEntity.java:227)
	at TRANSFORMER/create_mechanical_extruder@1.20.1-1.5.4.d-9/com.oierbravo.createmechanicalextruder.components.extruder.ExtruderBlockEntity.write(ExtruderBlockEntity.java:172)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.blockEntity.SmartBlockEntity.m_183515_(SmartBlockEntity.java:159)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.entity.BlockEntity.m_187482_(BlockEntity.java:77)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.entity.BlockEntity.m_187480_(BlockEntity.java:64)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.ponder.PonderWorld.lambda$createBackup$2(PonderWorld.java:84)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.ponder.PonderWorld.createBackup(PonderWorld.java:84)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.ponder.PonderRegistry.compile(PonderRegistry.java:77)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.ponder.PonderRegistry.compile(PonderRegistry.java:53)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.ponder.ui.PonderUI.of(PonderUI.java:123)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.ponder.PonderTooltipHandler.deferredTick(PonderTooltipHandler.java:67)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.ponder.PonderTooltipHandler.addToTooltip(PonderTooltipHandler.java:87)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.events.ClientEvents.addToItemTooltip(ClientEvents.java:260)
	at TRANSFORMER/create@0.5.1.d/com.simibubi.create.foundation.events.__ClientEvents_addToItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.1.47/net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:360)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:763)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_280553_(CreativeModeInventoryScreen.java:659)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_88315_(CreativeModeInventoryScreen.java:650)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109)
	at TRANSFORMER/forge@47.1.47/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427)
	at TRANSFORMER/forge@47.1.47/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965)
	... 18 more
```

Crash report: https://pastebin.com/sYJ2Js2s

**Comment by oierbravo** [comment]
Thanks for the report! I really appreciate all the data you provided.
